### ISSUE TITLE
hope the ssl=yes item can be configurable

### ISSUE THREAD

**Issue by timmyz** [britannic/EdgeMax-RFC2136-DDNS#5]
https://github.com/britannic/EdgeMax-RFC2136-DDNS/blob/1ac20868df029c73f77a5b3d88dd91eda0b01092/1.10.vyatta-dynamic-dns.pl#L138

the background is some ddns provider not supportable for ssl or the ssl service is just for paid users rather than free users. so just think this option should be configurable, let the user makes the choice.

**Comment by britannic** [comment]
Disabling is a security risk for a variety of reasons, so this shouldn’t be optional. You’re welcome to fork the code and make your own modifications.

**Comment by timmyz** [comment]
> Disabling is a security risk for a variety of reasons, so this shouldn’t be optional. You’re welcome to fork the code and make your own modifications.

my point is that surely the default setting is make it `ssl=yes` for most users. but it's better to give an entrance or a mechanism that some particular user can change the value. maybe a new configure input field in the EdgeOS UI  of ddns page, or make use of the optional input field, like `param1=value1;param2=value2;ssl=no` format.

now i can only hard code the logic of `vyatta-dynamic-dns.pl` file to fulfill that.
